package io.github.stoicswe.eyeandsickle.engine.rules;

import io.github.stoicswe.eyeandsickle.protocol.game.ComputeConsumer;
import io.github.stoicswe.eyeandsickle.engine.Balance;
import io.github.stoicswe.eyeandsickle.engine.state.AllocationState;
import io.github.stoicswe.eyeandsickle.engine.state.BreachState;
import io.github.stoicswe.eyeandsickle.engine.state.GameSave;
import io.github.stoicswe.eyeandsickle.engine.state.TaskState;
import java.time.Instant;

/**
 * How much racket the rig is making right now — the number the status strip's meter draws.
 *
 * <h2>Noise is not load, and this class exists because that kept being forgotten</h2>
 *
 * {@code docs/design/08-stealth-and-noise.md} §1: "noise is generated by <b>acting</b>". Three
 * invariants say which acts do not count, and each of them collapses a system if it is broken:
 *
 * <ul>
 *   <li><b>I4</b> — self-mining is immune to detection and generates zero heat. It is the income
 *       floor; a floor that made you loud would not be one, and the whole quiet-play strategy the
 *       economy is built to reward would stop existing.
 *   <li><b>I9</b> — defending your own rig never generates heat. Being wanted must come from
 *       aggression, never from self-defence.
 *   <li>{@code docs/design/04-mining.md} §3.1 — auditing your own rig is free and silent, which is
 *       what makes the discrepancy hunt a thing a player can afford to do often.
 * </ul>
 *
 * So a rig at 100% load on <b>solo</b> self-mining, defences and local scans reads <b>zero</b> here.
 * That is the headline result and it is correct rather than a bug.
 *
 * <p>⚠ <b>Pooled self-mining is the one exception, and it is a small one.</b> A pooled miner holds an
 * open connection to a pool and pushes a share up it every thirty seconds — that is outbound traffic
 * to a third party, which is exactly what this class counts, so it reads a couple of cycles rather
 * than nothing. Solo mining is genuinely silent: the work is local and nothing leaves the rig until a
 * block is found. <b>I4 is intact</b> — it grants immunity to detection and seizure and zero heat, and
 * a pooled rig still has all three; noise is a rate and nothing turns this trickle into heat. See
 * {@code Balance.POOL_SHARE_NOISE_CYCLES}, and note that it does not scale with allocation, because a
 * share is a small fixed packet however much hashing produced it.
 *
 * <h2>⚠ This lived in the client until 2026-07-27, and that was the wrong house</h2>
 *
 * {@code client/view/RigStatus} computed it, which meant three invariants were being enforced by a
 * view class — the one place {@code docs/design/00-vision-and-pillars.md} §4 says a rule may never
 * live, and the one place a home server's answer could not reach. It moved here so that the rule has
 * one implementation for both session modes and so the client is once again only drawing what it is
 * told.
 *
 * <h2>Two contributions, and only one of them is an allocation</h2>
 *
 * <ol>
 *   <li><b>Held cycles on outward consumers.</b> {@code CONTROL_CHANNEL}, {@code RELAY_HOP} and
 *       {@code BOT_FRAME} are work that reaches other machines. {@code DEPLOYED_MINER} is
 *       deliberately excluded even though it crosses a network: by <b>I6</b> a deployed miner is
 *       charged to the <em>host's</em> rig, so seeing one in your own budget means somebody else's
 *       miner is running on you — that is their noise, and counting it would make being a victim look
 *       like being an aggressor.
 *   <li><b>A running task's stated loudness</b>, {@link TaskState#noiseCycles}. A sweep occupies
 *       almost none of the rig and is one of the loudest things a player can do, so a task declares
 *       its own noise rather than having it derived from its cycles — see
 *       {@code Balance.NET_SWEEP_BASE_NOISE} for why the two were split, and {@code TaskState} for
 *       why the declaration lives on the task instead of in a switch here.
 *   <li><b>An open breach.</b> Being inside somebody else's machine is an act, and it grows louder as
 *       the player does louder things in it — see {@link #breachNoise}.
 * </ol>
 *
 * <h2>Loud while it runs, silent the moment it stops</h2>
 *
 * Both contributions are strictly present-tense. A recovering allocation is excluded, and a task is
 * counted only while {@code now} is inside its window — so the meter falls back to whatever the rig
 * was doing the instant the sweep settles. Noise is a <b>rate</b>. What a loud act leaves behind is
 * <em>heat</em>, which is a different field, persisted, and charged by different rules; conflating
 * the two would give the player a number that never came down and no way to read the difference
 * between "I am being loud" and "I have been loud".
 */
public final class NoiseRules {

    private NoiseRules() {}

    /**
     * Noise as a fraction of the rig's capacity, 0–1.
     *
     * @param now the session clock. ⚠ Never {@code Instant.now()} — a running sweep's window is
     *     measured against this, and a rule that reached for the wall clock behind its caller's back
     *     would report a test clock's sweeps as long over and a paused game's as still shouting
     */
    public static double level(GameSave save, Instant now) {
        if (save == null || save.rig == null || save.rig.totalCycles <= 0) {
            return 0.0d;
        }
        return Math.min(1.0d, outwardCycles(save, now) / (double) save.rig.totalCycles);
    }

    /**
     * The raw figure behind {@link #level}, in cycles.
     *
     * <p>Published separately because the readout says both — a fraction fills the meter and the
     * cycle count is what a player reasons with when deciding whether they can afford to be seen.
     */
    public static long outwardCycles(GameSave save, Instant now) {
        if (save == null) {
            return 0L;
        }
        long sum = 0L;
        if (save.rig != null && save.rig.allocations != null) {
            for (AllocationState allocation : save.rig.allocations) {
                if (!"ACTIVE".equals(allocation.state)) {
                    // Recovering cycles are cycles the player has already stopped spending on
                    // somebody else's machine. They are unavailable, which is a load fact, not a
                    // loudness one.
                    continue;
                }
                if (reachesOutward(allocation.consumer)) {
                    sum += allocation.cycles;
                }
            }
        }
        sum += taskNoise(save, now);
        sum += breachNoise(save);
        sum += spikeNoise(save, now);
        sum += MiningRules.poolNoiseCycles(save.rig);
        sum += Botnet.noiseCycles(save);
        return sum;
    }

    /**
     * How loud the open breach is, or zero.
     *
     * <h2>Quieter than a sweep, and never silent</h2>
     *
     * A sweep touches every machine within reach and announces itself to all of them; a breach is one
     * connection to one machine. So the ceiling here sits below the <em>cheapest</em> sweep's floor —
     * {@code Balance.BREACH_NOISE_CEILING} against {@code NET_SWEEP_BASE_NOISE} — and that ordering
     * is a balance statement rather than an accident of tuning. A breach that could out-shout a sweep
     * would make the sweep ladder's price read as a mistake.
     *
     * <p>But it starts at a floor rather than at zero, because being inside a machine that is not
     * yours is an act and {@code docs/design/08-stealth-and-noise.md} §1 charges acts. Without the
     * floor the safest possible play would be to sit in a breach indefinitely.
     *
     * <p>It <b>climbs with what the player does in there</b>. A run of quiet reads barely moves it; a
     * bypass adds twelve at a stroke and a tripped canary adds four. That is the same choice
     * {@code docs/design/05} §4 already prices in trace, showing up on the outside of the puzzle — and
     * having both is what stops "bypass everything" being free the moment the trace bar is survivable.
     *
     * <p>And it climbs faster on an <b>offset cipher</b>, by {@code Balance.BREACH_CIPHER_NOISE_FACTOR}.
     * That puzzle has no clock — the player may sit and subtract for as long as they like — so the
     * thing that answers "why not take all day" is that all day is spent on somebody else's wire.
     *
     * <h2>⚠ A crack is silent, on every outcome</h2>
     *
     * Invariant <b>I9</b>. A crack is a breach against a process on the player's own rig; nothing
     * leaves the machine, so there is nothing for anyone to hear. That is what makes it safe to lose
     * repeatedly and therefore usable as the tutorial ({@code docs/design/04-mining.md} §5.1), and a
     * crack that ticked the noise meter would quietly undo it.
     *
     * <p>A <em>resolved</em> breach is silent too: the attempt is over, the connection is closed, and
     * what a loud one leaves behind is heat rather than noise. Noise is a rate.
     */
    private static long breachNoise(GameSave save) {
        BreachState breach = save.activeBreach;
        if (breach == null || !breach.outcome.isEmpty() || breach.minerCrack) {
            return 0L;
        }
        int points = Balance.breachNoisePoints(breach.puzzleClass, breach.noise);
        long made = Math.round(points * Balance.BREACH_NOISE_PER_POINT);
        return Math.min(Balance.BREACH_NOISE_CEILING, Balance.BREACH_NOISE_FLOOR + made);
    }

    /**
     * The declared loudness of every task still running at {@code now}.
     *
     * <p>Summed rather than maxed: two sweeps at once is two lots of packets on two sets of machines,
     * and a player who starts a second one before the first has settled has genuinely doubled what
     * they are radiating. {@link #level} clamps the total, so this cannot read past a full meter.
     *
     * <p>⚠ A task that has passed its end but has not been settled yet contributes nothing. Settling
     * happens on a tick and the meter is read on a repaint, so between the two there is a window of
     * up to one frame in which a finished sweep is still on {@code save.tasks} — counting it would
     * make the meter hold a moment past the countdown reaching zero, which is precisely the
     * "contributes after it has finished" behaviour this model exists to rule out.
     */
    /**
     * A transient burst that has not expired yet — currently only an abandoned breach.
     *
     * <p>⚠ Measured against the session clock like everything else here. A spike compared against
     * {@code Instant.now()} would expire while the game was closed <em>and</em> report a test
     * clock's spikes as long over, which is the bug {@link #level}'s own parameter comment exists
     * to prevent.
     */
    private static long spikeNoise(GameSave save, Instant now) {
        if (save.noiseSpikeCycles <= 0 || save.noiseSpikeUntil == null || now == null) {
            return 0L;
        }
        return now.isBefore(save.noiseSpikeUntil) ? save.noiseSpikeCycles : 0L;
    }

    private static long taskNoise(GameSave save, Instant now) {
        if (save.tasks == null || now == null) {
            return 0L;
        }
        long sum = 0L;
        for (TaskState task : save.tasks) {
            if (task.noiseCycles > 0 && !task.isFinishedAt(now)) {
                sum += task.noiseCycles;
            }
        }
        return sum;
    }

    /**
     * Whether a consumer's held cycles are work that reaches other machines.
     *
     * <p>Exhaustive over {@link ComputeConsumer} on purpose — no {@code default}. A new consumer must
     * be classified by whoever adds it, at compile time, rather than defaulting to silent and being
     * discovered by a player who was loud and had no way to tell.
     */
    private static boolean reachesOutward(String consumer) {
        ComputeConsumer kind;
        try {
            kind = ComputeConsumer.valueOf(consumer);
        } catch (IllegalArgumentException | NullPointerException unknown) {
            // A hand-edited save. Silent rather than loud: inventing noise from a value nothing in
            // this build wrote would be unaccountable on a meter whose job is to be accounted for.
            return false;
        }
        return switch (kind) {
            case CONTROL_CHANNEL, RELAY_HOP -> true;
            // ⚠ BOT_FRAME IS COUNTED SEPARATELY, NOT SILENTLY, and this is the one consumer whose
            // held cycles are not its loudness. docs/design/10 §5a's Dampener cuts what a bot adds
            // to the pool and EfficientMultiThreading raises it, so the figure has to be modifiable
            // while the RESERVATION stays exactly what the rig holds. Botnet.noiseCycles is added to
            // the total in outwardCycles above. ⚠ Folding the modifiers into the allocation instead
            // would have made a quiet bot a CHEAP one, which is a different and much larger change:
            // the control channel is design/10 §3's self-correcting cap on botnet size.
            case BOT_FRAME -> false;
            // ⚠ SHELL_SESSION is OUTWARD, and it has to be. A shell held open on somebody else's
            // machine is a live connection to it — the single most visible thing an operator can be
            // doing short of a sweep. If sitting on eight machines were silent, the quietest way to
            // play would be to hold footholds indefinitely and never sweep again, which turns the
            // whole noise model off. It is the cheapest outward thing in the game per cycle; it is
            // not free.
            case SHELL_SESSION -> true;
            // ⚠ SELF_MINING stays false. The held CYCLES are local grinding in both modes; what is
            // outward about a pooled rig is its share submissions, which are counted separately in
            // MiningRules.poolNoiseCycles because they are a fixed trickle rather than a share of the
            // allocation. Flipping this flag instead would have made noise scale with hashrate, which
            // is wrong in fact and would have punished the income floor for being used.
            case SELF_MINING, DEFENSIVE_ARRAY, ACTIVE_TOOL, DEPLOYED_MINER -> false;
        };
    }
}
