-- ===========================================================================
-- V2 — core game state.
--
-- Every table below is SERVER-OWNED game state (Invariant I14). None of it is
-- ever written to a player's AT Protocol PDS, and none of it is ever accepted
-- from a client without validation. AT Proto supplies a DID and nothing else.
--
-- This migration satisfies the five FIRM constraints in
-- docs/architecture/06-data-model.md §1. The table sketches in that doc's §2
-- are tagged [PROPOSAL]; where the sketch and the design docs disagree, the
-- design docs win and the deviation is called out in a comment beginning
-- "DEVIATION FROM 06 §2".
--
--   1. All game state lives here.                                     (I14)
--   2. The public ledger is FIRST-CLASS ROWS, not a derived view.
--      docs/design/01-core-resources.md §2.2 — investigators, player and NPC,
--      follow ethecoin flows to build evidence. Indexed for BOTH counterparties.
--   3. Provenance chains queryable by item_id with chain_depth range access.
--      docs/architecture/04-item-provenance.md §6.1.
--   4. The compute ledger is reconstructable and fully attributable, and a
--      DISCREPANCY between a rig's ceiling and the sum of its allocations is
--      REPRESENTABLE — that discrepancy is the manual-audit signal for a hidden
--      hostile miner (docs/design/04-mining.md §3.1). Nothing here prevents one.
--   5. faction_reputation and validator_reputation are DIFFERENT THINGS.
--      Faction reputation lives in this file, in `faction_reputations`, keyed by
--      player_id. Validator reputation lives in db/migration/federation, in
--      `validators`, keyed by a SERVER's DID. No shared column, no shared key,
--      and therefore no join path. See docs/design/glossary.md.
--
-- CONVENTIONS ESTABLISHED HERE (the other systems build on these):
--
--   * uuid primary keys, generated by the server, never by the client.
--   * TIMESTAMP WITH TIME ZONE everywhere. Never `timestamp`; a self-hoster in a different
--     zone must not get a different game.
--   * Enumerations are `text` + a named CHECK, not PostgreSQL ENUM types. Enum
--     values are cheap to add and effectively impossible to remove or rename,
--     and half these vocabularies are still [PROPOSAL]. The Java side maps them
--     with exhaustive switches (server `persistence/EnumColumns`), so a renamed
--     constant is a compile error and `SchemaVocabularyTest` proves the Java
--     spellings and these CHECK lists agree.
--   * Ethecoin columns are `numeric(78,0)` named `*_wei` — integral wei, 1e-18
--     EC, per protocol `Ethecoin`. ⚠ NOT bigint: at 18 decimals a bigint tops
--     out at 9.22 EC, less than one firmware image. Cycle columns are named
--     `*_cycles`. The suffixes are load-bearing: `persistence/EconomyColumns`
--     refuses to read an ethecoin amount out of a cycles column, which is
--     Invariant I1 made mechanical at the persistence boundary.
--   * `row_version` on every row that a concurrent request can mutate. Updates
--     are `... SET row_version = row_version + 1 WHERE id = ? AND row_version = ?`.
--   * JSON for genuinely document-shaped data only: signed payloads, item
--     attrs, installed modules. Everything relational stays relational
--     (docs/architecture/06 §4).
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- Shared validation helper.
--
-- A DID is the portable player/server identity (docs/architecture/02 §1) and it
-- appears in a dozen columns across two migrations. Keeping the shape rule in
-- ONE immutable function means it cannot drift between tables; inlining the
-- regex twelve times means it eventually will. This is a shape check, not an
-- authentication check — proving a DID resolves to a key is the server's job at
-- sign-in, and no CHECK constraint can do it.
-- ---------------------------------------------------------------------------
CREATE ALIAS is_did FOR "io.github.stoicswe.eyeandsickle.server.identity.Did.isWellFormed";

-- ---------------------------------------------------------------------------
-- JSON shape checks, replacing Postgres's jsonb_typeof().
--
-- Two aliases, not one with a parameter: 'object' and 'array' are different
-- constraints, and a single shared helper is what let a careless edit briefly
-- turn every array check into an object check during the port. Named methods
-- make that mistake visible in the constraint itself.
-- ---------------------------------------------------------------------------
CREATE ALIAS is_json_object FOR "io.github.stoicswe.eyeandsickle.server.persistence.JsonShape.isJsonObject";
CREATE ALIAS is_json_array FOR "io.github.stoicswe.eyeandsickle.server.persistence.JsonShape.isJsonArray";
CREATE ALIAS json_array_length FOR "io.github.stoicswe.eyeandsickle.server.persistence.JsonShape.jsonArrayLength";




-- ---------------------------------------------------------------------------
-- server_state — the one row that describes this home server itself.
--
-- Server heat (docs/design/01-core-resources.md §4.2) is the average Sickle
-- activity across the population. It drives institutional Eye escalation that
-- affects EVERYONE and gates world-state narrative thresholds, so it is a
-- property of the server, not of any player — which is exactly why it cannot
-- live on `players` and why it needs a row of its own.
--
-- Singleton by construction: the primary key is a boolean pinned to true, so a
-- second row is a primary-key violation rather than a silent second world.
--
-- No thresholds or bands are stored. What each server-heat level unlocks is
-- open question N-1 (docs/design/15 §2) and inventing bands here would promote a
-- [PROPOSAL] to a decision in the hardest place to walk one back.
-- ---------------------------------------------------------------------------
CREATE TABLE server_state (
    only_row            boolean     DEFAULT TRUE PRIMARY KEY,
    -- This server's own DID. It is the `issuerDid` on every provenance record
    -- this server signs (docs/architecture/04 §2), so it must be set before the
    -- first mint — but it is unknown at migration time, hence nullable.
    server_did          text        NULL,
    server_heat         numeric(12, 4) NOT NULL DEFAULT 0,
    heat_updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    row_version         bigint      NOT NULL DEFAULT 0,

    CONSTRAINT ck_server_state_singleton         CHECK (only_row),
    CONSTRAINT ck_server_state_did_shape         CHECK (server_did IS NULL OR is_did(server_did)),
    CONSTRAINT ck_server_state_heat_non_negative CHECK (server_heat >= 0),
    CONSTRAINT ck_server_state_row_version       CHECK (row_version >= 0)
);

COMMENT ON TABLE server_state IS
    'Server-scoped state; exactly one row. Holds serverHeat (docs/design/01-core-resources.md §4.2) '
    'and this server''s own DID (docs/architecture/02-identity-and-auth.md).';
COMMENT ON COLUMN server_state.server_heat IS
    'Population-wide Eye attention. Distinct from players.personal_heat (§4.1) and from noise (§3).';

-- Seeded so that "read the server state" never has to handle an absent row —
-- an absent singleton is a null-check that every future caller would have to
-- remember, and one of them would not.
INSERT INTO server_state (only_row) VALUES (true);


-- ---------------------------------------------------------------------------
-- allowlist_entries — Minecraft-style access control.
--
-- docs/architecture/03-server-and-federation.md §1: a home server is private by
-- default and the operator chooses who joins. application.yml seeds an operator
-- list from the environment; this table is the durable, auditable form of the
-- same thing, so an operator can add and revoke without a restart.
--
-- Revocation is SOFT (a timestamp, not a DELETE). Who was allowed in, and when
-- they stopped being allowed in, is exactly the record an operator wants after
-- an incident; a DELETE destroys it.
-- ---------------------------------------------------------------------------
CREATE TABLE allowlist_entries (
    entry_id      uuid        PRIMARY KEY,
    did           text        NOT NULL,
    added_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    added_by_did  text        NULL,
    note          text        NULL,
    revoked_at    TIMESTAMP WITH TIME ZONE NULL,
    revoked_by_did text       NULL,

    CONSTRAINT uq_allowlist_entries_did          UNIQUE (did),
    CONSTRAINT ck_allowlist_entries_did_shape    CHECK (is_did(did)),
    CONSTRAINT ck_allowlist_entries_added_by     CHECK (added_by_did IS NULL OR is_did(added_by_did)),
    CONSTRAINT ck_allowlist_entries_revoked_by   CHECK (revoked_by_did IS NULL OR is_did(revoked_by_did)),
    CONSTRAINT ck_allowlist_entries_revoked_time CHECK (revoked_at IS NULL OR revoked_at >= added_at),
    -- Both markers agree or neither does. A revocation with no actor is an
    -- unattributable moderation action, which is the one kind an operator will
    -- later need to explain.
    CONSTRAINT ck_allowlist_entries_revoked_pair CHECK ((revoked_at IS NULL) = (revoked_by_did IS NULL))
);

COMMENT ON TABLE allowlist_entries IS
    'Operator-controlled join allowlist (docs/architecture/03-server-and-federation.md §1). '
    'Revocation is soft so the moderation history survives.';

-- The hot query is "may this DID join right now", asked once per sign-in.
CREATE INDEX ix_allowlist_entries_active ON allowlist_entries (did);


-- ---------------------------------------------------------------------------
-- players.
--
-- The DID is the portable identity (docs/architecture/02 §1); player_id is this
-- server's local key. Both exist on purpose: the DID travels between servers and
-- signs provenance, the uuid is what every foreign key here points at, so a
-- future DID rotation is one UPDATE rather than a cascade through the schema.
--
-- `did` is NULLABLE for local-only solo play, which docs/architecture/02 §4
-- leaves explicitly open. Note the consequence, because it is real and
-- unresolved: `items.holder_did` is a DID, so a player with no DID cannot hold a
-- provenanced item. Resolving §4 either assigns local players a server-local
-- DID-shaped identifier or restricts them to a DID-less item model.
--
-- DEVIATION FROM 06 §2: no `faction_reputation` column here. See
-- `faction_reputations` below.
-- ---------------------------------------------------------------------------
CREATE TABLE players (
    player_id                 uuid        PRIMARY KEY,
    did                       text        NULL,
    -- The current display handle. NOT an identity: handles change, DIDs do not
    -- (docs/architecture/02 §2). Never join on this.
    handle                    text        NULL,
    faction                   text        NOT NULL DEFAULT 'none',
    -- Long-horizon Eye attention accrued from this player's own actions
    -- (docs/design/01-core-resources.md §4.1). Distinct from noise, which is
    -- short-horizon, decaying and not persisted here.
    personal_heat             numeric(12, 4) NOT NULL DEFAULT 0,
    -- The authoritative spendable balance.
    --
    -- ADDITION TO 06 §2, and a deliberate one: constraint 2 makes the ledger
    -- first-class ROWS (it is an evidence surface, not bookkeeping), but it does
    -- not say a balance must be re-summed from genesis on every purchase. The
    -- balance is materialised here and the ledger row is written in the SAME
    -- transaction; neither is meaningful without the other. A reconciliation job
    -- comparing the two is the anti-tamper check, and it only works because both
    -- exist.
    -- ⚠ numeric(78,0), NOT bigint. An ethecoin divides to 18 places (wei, exactly ether's
    -- relationship to its own base unit), and at that scale a bigint tops out at 9.22 EC — less
    -- than one firmware image.
    ethecoin_balance_wei      numeric(78, 0) NOT NULL DEFAULT 0,
    -- Save slot within the account (docs/architecture/09 §1). 1..16 is a structural bound for a
    -- DID-bound character; NULL for a local, DID-less one, which is exempt from the cap. The
    -- product cap (default 3) is enforced in the service from EYEANDSICKLE_MAX_CHARACTERS, not
    -- here (09 §2).
    slot                      smallint    NULL,
    -- Character lifecycle (09 §6.1). migrated/retired are terminal shells kept for audit; a
    -- character in either state can never be played or migrated again — no double-play.
    status                    text        NOT NULL DEFAULT 'active',
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    last_seen_at              TIMESTAMP WITH TIME ZONE NULL,
    row_version               bigint      NOT NULL DEFAULT 0,

    -- ⚠ (did, slot), NOT did alone. A DID is an ACCOUNT and may hold several characters
    -- (docs/architecture/09 §1, §8), so uniqueness is per slot within the account. Two DID-less
    -- local characters both key (NULL, NULL) and coexist, because a unique index treats NULLs as
    -- distinct.
    CONSTRAINT uq_players_did_slot         UNIQUE (did, slot),
    CONSTRAINT ck_players_did_shape        CHECK (did IS NULL OR is_did(did)),
    CONSTRAINT ck_players_status           CHECK (status IN ('active', 'migrated', 'retired')),
    -- A slot number without an account is meaningless and an account without one cannot be
    -- addressed, so the two are present or absent together.
    CONSTRAINT ck_players_slot_pairing     CHECK ((did IS NULL) = (slot IS NULL)),
    CONSTRAINT ck_players_slot_bound       CHECK (slot IS NULL OR slot BETWEEN 1 AND 16),
    CONSTRAINT ck_players_faction          CHECK (faction IN ('eye', 'sickle', 'none')),
    CONSTRAINT ck_players_heat_non_negative CHECK (personal_heat >= 0),
    -- Balances never go negative. "Can they afford it" is a question asked
    -- BEFORE the subtraction, on the server; a negative balance is the shape an
    -- unchecked purchase takes, and it must not be storable. Mirrors the same
    -- rule in protocol `Ethecoin`.
    CONSTRAINT ck_players_balance_non_negative CHECK (ethecoin_balance_wei >= 0),
    CONSTRAINT ck_players_row_version      CHECK (row_version >= 0)
);

COMMENT ON TABLE players IS
    'One row per player known to this home server. Identity from AT Proto (docs/architecture/02); '
    'ALL game state server-owned (Invariant I14).';
COMMENT ON COLUMN players.did IS
    'AT Protocol DID — the portable, stable identity. Nullable for local-only solo play '
    '(docs/architecture/02 §4, open).';
COMMENT ON COLUMN players.ethecoin_balance_wei IS
    'Spendable balance in wei (1e-18 EC). Materialised alongside the ledger row that moved it, in '
    'the same transaction, so the two can never disagree.';
COMMENT ON COLUMN players.slot IS
    'Save slot within the account (docs/architecture/09-player-state-portability.md §1). '
    '1..16 structural bound for a DID-bound character; NULL for a local, DID-less character (exempt from the cap). '
    'The product cap (default 3) is enforced in the service from EYEANDSICKLE_MAX_CHARACTERS, not here (09 §2).';
COMMENT ON COLUMN players.status IS
    'Character lifecycle (docs/architecture/09 §6.1): active | migrated | retired. '
    'migrated/retired are terminal shells kept for audit; a character in either state can never be played or '
    'migrated again (no double-play).';


-- ---------------------------------------------------------------------------
-- faction_reputations — a player's standing with ONE named faction.
--
-- ⚠⚠ THIS IS NOT VALIDATOR REPUTATION AND MUST NEVER BE JOINED TO IT. ⚠⚠
--
-- docs/design/glossary.md flags "reputation" as a word with two unrelated
-- meanings in this project:
--
--   * faction reputation (HERE)  — a PLAYER's Eye/Sickle standing. Moved by
--     in-fiction choices, gates economy-distorting items
--     (docs/design/02-unlock-gates.md §2.3), reset when a player abandons a
--     side. Losing it is a story beat.
--   * validator reputation (db/migration/federation/V1001, table `validators`)
--     — a federated SERVER's trust score, weighting quorum votes on cross-server
--     duel outcomes (docs/architecture/05-validator-quorum.md). Slashing it is
--     an anti-cheat action.
--
-- Different subject, different lifetime, different consequences. Constraint 5 of
-- docs/architecture/06 §1 requires separate tables with no shared column; this
-- schema goes further and shares no KEY either — one is keyed by player_id, the
-- other by a server's DID — so there is no expressible join between them.
--
-- DEVIATION FROM 06 §2, which put a single `faction_reputation` numeric column
-- on `players`. docs/design/01-core-resources.md §5 describes "per-faction
-- standing (Eye / Sickle)" that only "eventually forces a binary commitment", so
-- a player can hold standing with both sides before committing. One column
-- cannot represent that. `players.faction` still records the commitment.
--
-- The scale is [PROPOSAL] P-11 (docs/design/15 §2): 06 types it `numeric` and no
-- doc says whether standing may go negative. Modelled as an integral score
-- permitting negatives, matching protocol `FactionReputation`. No tiers or
-- thresholds are stored — classifying a standing is a balance decision and
-- belongs to the server's rules layer, not to the schema.
-- ---------------------------------------------------------------------------
CREATE TABLE faction_reputations (
    player_id   uuid        NOT NULL REFERENCES players (player_id) ON DELETE CASCADE,
    faction     text        NOT NULL,
    standing    bigint      NOT NULL DEFAULT 0,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    row_version bigint      NOT NULL DEFAULT 0,

    CONSTRAINT pk_faction_reputations PRIMARY KEY (player_id, faction),
    -- Standing with nobody is a category error, not a smaller standing: a player
    -- who abandoned a side has zero standing with a NAMED faction. Same rule the
    -- protocol record enforces.
    CONSTRAINT ck_faction_reputations_named_faction CHECK (faction IN ('eye', 'sickle')),
    CONSTRAINT ck_faction_reputations_row_version   CHECK (row_version >= 0)
);

COMMENT ON TABLE faction_reputations IS
    'Player standing with a named faction (docs/design/01-core-resources.md §5). '
    'NOT validator reputation — see docs/architecture/05 and the `validators` table; no join path exists.';


-- ---------------------------------------------------------------------------
-- rigs — the machine, and therefore the compute ceiling.
--
-- `total_cycles` is the master scarcity's ceiling (docs/design/01 §1; a starting
-- rig is 100). It is raised ONLY by schematics and story milestones
-- (docs/design/11-rig-infrastructure.md) and NEVER by ethecoin — Invariant I1.
-- Any code path that writes this column while also touching a balance is a bug
-- in the shape the whole economy is built to prevent.
--
-- DEVIATION FROM 06 §2: the sketch's `compute_cores` is renamed `total_cycles`.
-- It is measured in cycles, and the `*_cycles` suffix is what lets
-- `persistence/EconomyColumns` refuse to read it as an ethecoin amount.
-- ---------------------------------------------------------------------------
CREATE TABLE rigs (
    rig_id              uuid        PRIMARY KEY,
    player_id           uuid        NOT NULL REFERENCES players (player_id) ON DELETE CASCADE,
    total_cycles        integer     NOT NULL,
    -- Governs how fast spent cycles come back, and slows as load approaches
    -- capacity (docs/design/01 §1.3). The curve itself is a server-side balance
    -- value; only the tier is stored.
    thermal_budget_tier integer     NOT NULL DEFAULT 1,
    bandwidth           integer     NOT NULL,
    memory_buffer       integer     NOT NULL,
    -- Isolated Partition, Firmware Implant, Worm, Cuckoo Patch, Payout Splitter
    -- (docs/design/11-rig-infrastructure.md). JSON because the module set is
    -- open and each module carries its own shape; a column per module would mean
    -- a migration per module.
    installed_modules   JSON       NOT NULL DEFAULT JSON '{}',
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    row_version         bigint      NOT NULL DEFAULT 0,

    CONSTRAINT ck_rigs_total_cycles      CHECK (total_cycles > 0),
    CONSTRAINT ck_rigs_thermal_tier      CHECK (thermal_budget_tier >= 1),
    CONSTRAINT ck_rigs_bandwidth         CHECK (bandwidth > 0),
    CONSTRAINT ck_rigs_memory_buffer     CHECK (memory_buffer >= 0),
    CONSTRAINT ck_rigs_modules_are_object CHECK (is_json_object(installed_modules)),
    CONSTRAINT ck_rigs_row_version       CHECK (row_version >= 0)
);

COMMENT ON TABLE rigs IS
    'A player''s machine. total_cycles is the compute ceiling (docs/design/01-core-resources.md §1); '
    'never purchasable with ethecoin (Invariant I1).';

CREATE INDEX ix_rigs_player ON rigs (player_id);


-- ---------------------------------------------------------------------------
-- compute_allocations — the compute ledger. Constraint 4 lives here.
--
-- TWO RIGS PER ROW, BECAUSE OF INVARIANT I6.
--
-- "A deployed miner consumes the HOST's compute, not the deployer's." That one
-- rule means an allocation cannot be described by a single rig:
--
--   * the HOST's ledger carries a `deployed_miner` row charged to the host,
--     whose counterparty is the deployer's rig;
--   * the DEPLOYER's ledger carries a `control_channel` row charged to the
--     deployer (3 cycles, docs/design/04 §2), whose counterparty is the host.
--
-- Two rows on two rigs, not one row seen from two sides. Collapsing them —
-- "the miner costs 20 cycles, charge it once" — is the exact mistake I6 exists
-- to prevent, and it deletes the reason a host ever spends compute on detection.
-- `counterparty_rig_id` is INFORMATIONAL: it names the far end, never a second
-- charge.
--
-- ⚠ WHAT IS DELIBERATELY NOT CONSTRAINED HERE ⚠
--
-- There is NO constraint that the sum of a rig's allocations stays within
-- `rigs.total_cycles`, and there must never be one. docs/architecture/06 §1
-- constraint 4 and docs/design/04 §3.1 make the DISCREPANCY the gameplay: a
-- rootkit-wrapped miner (docs/design/09) steals the host's cycles while being
-- absent from what the host is shown, and "cycle totals that don't add up" is
-- how a careful player finds it. A database constraint that made the numbers
-- always add up would delete the manual-audit loop by way of a tidy refactor.
-- See protocol `ComputeBudget#unaccountedFor()` for the client-side half.
--
-- Concealment is NOT modelled as a column here. A rootkit-wrapped miner's row
-- exists and is charged; whether it is DISCLOSED is derived from
-- `deployed_miners.rootkit_wrapped` at read time. Two columns saying the same
-- thing would eventually say different things.
-- ---------------------------------------------------------------------------
CREATE TABLE compute_allocations (
    allocation_id       uuid        PRIMARY KEY,
    -- The rig whose ceiling these cycles count against: the HOST for a foreign
    -- miner, the DEPLOYER for a control channel.
    charged_rig_id      uuid        NOT NULL REFERENCES rigs (rig_id) ON DELETE CASCADE,
    -- The far end of a cross-rig relationship, or NULL for a purely local
    -- allocation (the common case).
    counterparty_rig_id uuid        NULL REFERENCES rigs (rig_id) ON DELETE SET NULL,
    consumer_type       text        NOT NULL,
    -- The specific miner / bot / tool, or NULL where the consumer is not a
    -- distinct entity (self-mining is the rig itself). No FK: the referent lives
    -- in a different table per consumer_type, and several of those tables belong
    -- to systems that are still [PROPOSAL].
    consumer_ref        uuid        NULL,
    allocated_cycles    integer     NOT NULL,
    state               text        NOT NULL,
    recovers_at         TIMESTAMP WITH TIME ZONE NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    row_version         bigint      NOT NULL DEFAULT 0,

    CONSTRAINT ck_compute_allocations_consumer CHECK (consumer_type IN (
        'active_tool', 'bot_frame', 'self_mining', 'control_channel',
        'deployed_miner', 'defensive_array', 'relay_hop', 'shell_session')),
    CONSTRAINT ck_compute_allocations_state    CHECK (state IN ('active', 'recovering')),
    CONSTRAINT ck_compute_allocations_cycles   CHECK (allocated_cycles >= 0),
    -- A counterparty equal to the charged rig is not a harmless redundancy: it
    -- is the shape a double-charge takes when someone "simplifies" I6 away, and
    -- it reads on screen as a rig hosting a parasite for itself.
    CONSTRAINT ck_compute_allocations_two_rigs CHECK (charged_rig_id IS DISTINCT FROM counterparty_rig_id),
    -- Both markers agree. A recovering row without a time cannot satisfy
    -- docs/design/01 §1.4's "with time-to-recover"; an active row carrying one is
    -- claiming to be two states at once.
    CONSTRAINT ck_compute_allocations_recovery CHECK ((state = 'recovering') = (recovers_at IS NOT NULL)),
    CONSTRAINT ck_compute_allocations_row_version CHECK (row_version >= 0)
);

COMMENT ON TABLE compute_allocations IS
    'The compute ledger (docs/design/01-core-resources.md §1, docs/architecture/06 §1 constraint 4). '
    'Two rigs per row because of Invariant I6. A discrepancy against rigs.total_cycles is the '
    'manual-audit signal and is deliberately representable.';
COMMENT ON COLUMN compute_allocations.counterparty_rig_id IS
    'Informational far end of a cross-rig relationship. NEVER a second charge (Invariant I6).';

-- The HUD query: every row charged to one rig (docs/design/01 §1.4).
CREATE INDEX ix_compute_allocations_charged ON compute_allocations (charged_rig_id, state);
-- The audit query: "what is this rig of mine reaching out to", and the reverse
-- lookup a Provenance Tracer needs (docs/design/07-recon-tools.md).
CREATE INDEX ix_compute_allocations_counterparty ON compute_allocations (counterparty_rig_id);
-- The sweep that returns recovering cycles to the pool.
CREATE INDEX ix_compute_allocations_recovering ON compute_allocations (recovers_at);


-- ---------------------------------------------------------------------------
-- rig_compute_reconciliation — the authoritative arithmetic, in one place.
--
-- This view sums ALL allocations, including ones the server will choose not to
-- disclose to the player. That is the point: `available_cycles` here is the
-- truth, and the gap a player sees is created by omitting rows from the
-- RESPONSE, never by omitting them from this sum. Computing availability
-- ad-hoc in three services is how one of them eventually forgets the hidden
-- rows and hands a rootkit-wrapped miner free capacity.
-- ---------------------------------------------------------------------------
CREATE VIEW rig_compute_reconciliation AS
SELECT r.rig_id,
       r.player_id,
       r.total_cycles,
       COALESCE(SUM(a.allocated_cycles) FILTER (WHERE a.state = 'active'), 0)     AS active_cycles,
       COALESCE(SUM(a.allocated_cycles) FILTER (WHERE a.state = 'recovering'), 0) AS recovering_cycles,
       r.total_cycles - COALESCE(SUM(a.allocated_cycles), 0)                      AS available_cycles
  FROM rigs r
  LEFT JOIN compute_allocations a ON a.charged_rig_id = r.rig_id
 GROUP BY r.rig_id, r.player_id, r.total_cycles;

COMMENT ON VIEW rig_compute_reconciliation IS
    'Authoritative per-rig compute arithmetic over ALL allocations, disclosed or not. '
    'available_cycles may go negative — that is an over-subscribed rig, not an error.';


-- ---------------------------------------------------------------------------
-- items.
--
-- `item_attrs` mirrors the provenance payload's `itemAttrs`
-- (docs/architecture/04 §2): the provenance record IS the authoritative item
-- definition, not merely a receipt of one. This column is the queryable
-- projection of the chain tip, and it is only ever written from a verified
-- record — never from a client request.
--
-- Location is exactly one of: a storage tier, or a bot socket. protocol
-- `StorageTier` explains why socketing is not a fourth tier — docs/design/01 §6
-- closes the tier set at three, and docs/design/10 makes a socketed item
-- mid-risk by being OUT of the vault rather than by being in a fourth place.
-- ---------------------------------------------------------------------------
CREATE TABLE items (
    item_id      uuid        PRIMARY KEY,
    item_type    text        NOT NULL,
    item_attrs   JSON       NOT NULL DEFAULT JSON '{}',
    -- The current owner, as a DID, because that is what the provenance chain
    -- signs. No foreign key to players.did: a holder may be an NPC, or a remote
    -- DID mid-transfer, and players.did is itself nullable for local-only play.
    holder_did   text        NOT NULL,
    storage_tier text        NULL,
    -- The bot instance this item is socketed into (docs/design/10, [PROPOSAL]).
    -- No FK — bots are out of the Established spine and their table does not
    -- exist yet.
    socketed_in  uuid        NULL,
    acquired_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    row_version  bigint      NOT NULL DEFAULT 0,

    CONSTRAINT ck_items_holder_shape  CHECK (is_did(holder_did)),
    CONSTRAINT ck_items_attrs_object  CHECK (is_json_object(item_attrs)),
    CONSTRAINT ck_items_storage_tier  CHECK (storage_tier IS NULL
                                             OR storage_tier IN ('vault', 'standard_storage', 'high_hackable_zone')),
    -- Exactly one location. An item in a tier AND in a bot is two exposure
    -- levels at once, and the raid systems would disagree about which applies.
    CONSTRAINT ck_items_one_location  CHECK ((storage_tier IS NULL) <> (socketed_in IS NULL)),
    CONSTRAINT ck_items_row_version   CHECK (row_version >= 0)
);

COMMENT ON TABLE items IS
    'Items held on this server. item_attrs mirrors the provenance chain tip (docs/architecture/04 §2), '
    'which is the authoritative definition.';

CREATE INDEX ix_items_holder ON items (holder_did);
-- Raid targeting reads by exposure (docs/design/01 §6): the High-Hackable Zone
-- is raidable while the owner is offline, Standard Storage only while online.
CREATE INDEX ix_items_exposure ON items (storage_tier, holder_did);
CREATE INDEX ix_items_socketed ON items (socketed_in);


-- ---------------------------------------------------------------------------
-- provenance_records — the per-item signed chain. Constraint 3 lives here.
--
-- docs/architecture/04 §6: chains are PER-ITEM (decided in Tech Chat 2), so
-- "show this item's history" is walking one chain, and verifying an item never
-- means walking a chain full of unrelated events.
--
-- §6.1 requires two things for the player-facing history view, and this table
-- provides both:
--   1. records indexed by item_id;
--   2. `chain_depth` (genesis = 0) so the client can fetch "records N through
--      N+20" instead of walking from the tip every time.
-- The UNIQUE (item_id, chain_depth) index serves the range query AND enforces
-- one record per position — a second record at the same depth is a forked
-- history, which is what a fabricating server produces.
--
-- APPEND-ONLY, ENFORCED BY TRIGGER. A signed chain that can be edited in place
-- is not a chain. See the trigger below.
-- ---------------------------------------------------------------------------
CREATE TABLE provenance_records (
    record_id        uuid        PRIMARY KEY,
    -- ON DELETE RESTRICT, not CASCADE: deleting an item must not erase a signed
    -- history that other servers may still hold and verify against. Destroying
    -- an item (Invariant I11) is a state change owned by the item lifecycle, not
    -- a row deletion.
    item_id          uuid        NOT NULL,
    chain_depth      integer     NOT NULL,
    -- SHA-256 over the CANONICAL PAYLOAD bytes, rendered 'sha256-' + 64 lowercase
    -- hex — protocol `RecordHash`, [PROPOSAL] P-1 in docs/design/15 §2. Stored
    -- rather than recomputed so the chain link is checkable with an index lookup.
    record_hash      text        NOT NULL,
    prev_record_hash text        NULL,
    event_type       text        NOT NULL,
    holder_did       text        NOT NULL,
    -- The signing server's DID, or the synthetic 'duel:<duelId>' identifier for a
    -- quorum-issued outcome (docs/architecture/04 §3.1) — which is why this is
    -- NOT constrained to is_did().
    issuer_did       text        NOT NULL,
    record_version   integer     NOT NULL,
    -- The signed content, exactly as it was canonicalized.
    payload          JSON       NOT NULL,
    -- The full detached-JWS envelope as RECEIVED (docs/architecture/04 §3). This
    -- is the artifact a verifier re-checks; `payload` and `signatures` are
    -- projections of it extracted for query. Write all three from ONE parse, in
    -- one statement, or they will drift and the drift will look like cheating.
    envelope         JSON       NOT NULL,
    -- The signature blocks: one for a single-issuer record, one per validator
    -- for a duel outcome (§3.1). Extracted so "which duels did validator X sign"
    -- is answerable without parsing every envelope.
    signatures       JSON       NOT NULL,
    -- ISO-8601 string as signed, kept verbatim: it is inside the signed bytes and
    -- re-rendering it from a TIMESTAMP WITH TIME ZONE would change them (see protocol
    -- `ProvenancePayload`).
    payload_timestamp text       NOT NULL,
    recorded_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    -- NAMED, not inline on the column. An unnamed REFERENCES gets an engine-generated name —
    -- `provenance_records_item_id_fkey` in Postgres, `CONSTRAINT_66` in H2 — so a refusal
    -- identifies the rule only by accident of vendor. Naming it means the violation message says
    -- what was violated, which is the whole value of enforcing it here rather than in Java.
    CONSTRAINT fk_provenance_records_item     FOREIGN KEY (item_id)
                                              REFERENCES items (item_id) ON DELETE RESTRICT,
    CONSTRAINT uq_provenance_records_position UNIQUE (item_id, chain_depth),
    CONSTRAINT uq_provenance_records_hash     UNIQUE (record_hash),
    CONSTRAINT ck_provenance_records_depth    CHECK (chain_depth >= 0),
    CONSTRAINT ck_provenance_records_event    CHECK (event_type IN
        ('initial_mint', 'server_grant', 'trade', 'duel_grant')),
    CONSTRAINT ck_provenance_records_holder   CHECK (is_did(holder_did)),
    -- Genesis is defined by BOTH markers agreeing, the same discipline protocol
    -- `ProvenancePayload` applies. A record claiming depth 0 while chaining to a
    -- predecessor is a broken chain, and catching it here is cheaper than
    -- catching it during a verification walk.
    CONSTRAINT ck_provenance_records_genesis  CHECK ((chain_depth = 0) = (prev_record_hash IS NULL)),
    -- [PROPOSAL] P-5 (docs/design/15 §2): genesis must be an initial_mint and an
    -- initial_mint may appear only at genesis. The docs fix depth 0 + null
    -- prev hash but never fix the event type; the protocol verifier already
    -- rejects chains that violate this, so storing one would store an
    -- unverifiable chain.
    CONSTRAINT ck_provenance_records_mint     CHECK ((chain_depth = 0) = (event_type = 'initial_mint')),
    CONSTRAINT ck_provenance_records_payload  CHECK (is_json_object(payload)),
    CONSTRAINT ck_provenance_records_envelope CHECK (is_json_object(envelope)),
    CONSTRAINT ck_provenance_records_sigs     CHECK (is_json_array(signatures)
                                                     AND json_array_length(signatures) >= 1)
);

COMMENT ON TABLE provenance_records IS
    'Per-item signed history (docs/architecture/04-item-provenance.md §6). Append-only. '
    'UNIQUE (item_id, chain_depth) both serves §6.1 range queries and forbids a forked chain.';
COMMENT ON COLUMN provenance_records.envelope IS
    'The received detached-JWS envelope; authoritative. payload/signatures are extracted projections.';

-- Explicit index on item_id alone. The UNIQUE (item_id, chain_depth) index
-- already covers item_id as a leading column, so this is NOT redundant for
-- lookup — it is omitted deliberately. Recording that here so nobody adds it,
-- measures nothing, and calls it a fix (docs/architecture/06 §3: measure first).


-- ---------------------------------------------------------------------------
-- ledger_transactions — the public ledger. Constraint 2 lives here.
--
-- docs/design/01-core-resources.md §2.2: transactions are visible by default,
-- and this is a GAMEPLAY FEATURE, not blockchain flavour. NPC investigators (The
-- Eye) and player investigators follow ethecoin flows to build evidence, feeding
-- the informant/evidence system (docs/design/12). That is why these are
-- first-class rows and why they are indexed for BOTH counterparties: an
-- investigation runs in both directions — "where did this money go" and "who
-- paid for this".
--
-- A Dead Drop (docs/design/08) does not skip the ledger. The row is still
-- written; `traceable` is false, and the investigator-facing query is what
-- obscures it. Laundering is a gameplay verb, so it has to leave something
-- behind to be a verb at all.
--
-- APPEND-ONLY, ENFORCED BY TRIGGER. A ledger you can edit is not evidence.
-- Reversals are new rows.
-- ---------------------------------------------------------------------------
CREATE TABLE ledger_transactions (
    tx_id          uuid        PRIMARY KEY,
    -- NULL for a faucet: mining rewards and mints have no payer.
    from_did       text        NULL,
    to_did         text        NOT NULL,
    -- Magnitude only. Direction is from_did -> to_did; a sign would encode
    -- direction a second time, in a second place, and the two would eventually
    -- disagree. Same rule as protocol `Ethecoin`.
    amount_wei      numeric(78, 0) NOT NULL,
    tx_type        text        NOT NULL,
    traceable      boolean     NOT NULL DEFAULT true,
    -- Context an investigator can read: which miner, which duel, which vendor.
    -- JSON because the useful context differs per tx_type.
    memo           JSON       NOT NULL DEFAULT JSON '{}',
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    CONSTRAINT ck_ledger_from_shape   CHECK (from_did IS NULL OR is_did(from_did)),
    CONSTRAINT ck_ledger_to_shape     CHECK (is_did(to_did)),
    -- Zero-value transactions are noise in an evidence surface.
    CONSTRAINT ck_ledger_amount       CHECK (amount_wei > 0),
    -- Exactly the six types docs/architecture/06 §2 names. Dead Drops are NOT a
    -- seventh type — they are `traceable = false` on the type they actually are,
    -- which is what makes them hard to spot rather than trivially filterable.
    CONSTRAINT ck_ledger_tx_type      CHECK (tx_type IN (
        'mining_reward', 'trade', 'crack_seizure', 'raid_loot', 'payout_splitter', 'purchase')),
    CONSTRAINT ck_ledger_not_self     CHECK (from_did IS NULL OR from_did <> to_did),
    -- A mining reward is the economy's faucet and has no payer; everything else
    -- moves existing ethecoin between two parties. Crack seizure in particular is
    -- "a transfer, not a faucet" (docs/design/04 §5.1) — the buffer already
    -- exists on the host's machine, so no new currency enters the economy.
    CONSTRAINT ck_ledger_faucet       CHECK (from_did IS NOT NULL OR tx_type = 'mining_reward'),
    CONSTRAINT ck_ledger_memo_object  CHECK (is_json_object(memo))
);

COMMENT ON TABLE ledger_transactions IS
    'The public ledger (docs/design/01-core-resources.md §2.2) — first-class rows, an investigation '
    'surface, append-only. Indexed for both counterparties.';
COMMENT ON COLUMN ledger_transactions.traceable IS
    'False when moved via a Dead Drop (docs/design/08). The row still exists; investigator queries obscure it.';

-- Constraint 2, made real: an investigation runs from either end.
CREATE INDEX ix_ledger_from ON ledger_transactions (from_did, created_at DESC);
CREATE INDEX ix_ledger_to   ON ledger_transactions (to_did, created_at DESC);
-- The "recent activity" feed the ledger view opens on.
CREATE INDEX ix_ledger_recent ON ledger_transactions (created_at DESC);


-- ---------------------------------------------------------------------------
-- deployed_miners — parasites on other machines.
--
-- Invariant I6 again: the miner consumes the HOST's compute. The deployer's own
-- cost is a 3-cycle control channel (docs/design/04 §2), recorded as a
-- `control_channel` row in compute_allocations charged to the DEPLOYER's rig.
--
-- Invariant I5: these are the ONLY offline income source, and offline output
-- accrues into a buffer that lives ON THE HOST, capped, and must be collected on
-- return (§2.3). The buffer is the prize in a crack (§5.1).
--
-- DEVIATION FROM 06 §2: the sketch's untyped `host_ref uuid` is split into
-- `host_rig_id` (a real foreign key when the host is a player) and `host_npc_ref`
-- (when it is not). One untyped column pointing at two different things is a
-- referential-integrity hole in the exact place I6 is enforced.
-- ---------------------------------------------------------------------------
CREATE TABLE deployed_miners (
    miner_id          uuid        PRIMARY KEY,
    deployer_did      text        NOT NULL,
    -- The deployer's rig, which pays the control channel. NULL when the deployer
    -- is not local to this server (cross-server deployment) — the control channel
    -- is then charged on their home server, not here.
    deployer_rig_id   uuid        NULL REFERENCES rigs (rig_id) ON DELETE SET NULL,
    host_type         text        NOT NULL,
    host_rig_id       uuid        NULL REFERENCES rigs (rig_id) ON DELETE CASCADE,
    host_npc_ref      uuid        NULL,
    tier              text        NOT NULL,
    -- On-host accrual while the deployer is offline (§2.3). The CAP in hours is a
    -- column and not a constant because it is open question OQ-4 — 4 hours is a
    -- starting figure, and a starting figure that is hardcoded in fifty places is
    -- a starting figure forever.
    buffer_wei        numeric(78, 0) NOT NULL DEFAULT 0,
    buffer_cap_hours  integer     NOT NULL,
    -- Hidden from routine scans, but NOT from manual audit (docs/design/09,
    -- docs/design/04 §3.1). This flag decides disclosure; it never decides
    -- whether the compute_allocations row exists. The row always exists.
    rootkit_wrapped   boolean     NOT NULL DEFAULT false,
    state             text        NOT NULL DEFAULT 'live',
    deployed_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    buffer_updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    row_version       bigint      NOT NULL DEFAULT 0,

    CONSTRAINT ck_deployed_miners_deployer  CHECK (is_did(deployer_did)),
    CONSTRAINT ck_deployed_miners_host_type CHECK (host_type IN ('npc', 'player')),
    CONSTRAINT ck_deployed_miners_tier      CHECK (tier IN ('t1', 't2', 't3')),
    CONSTRAINT ck_deployed_miners_state     CHECK (state IN ('live', 'hijacked', 'sabotaged', 'dead')),
    CONSTRAINT ck_deployed_miners_buffer    CHECK (buffer_wei >= 0),
    CONSTRAINT ck_deployed_miners_cap       CHECK (buffer_cap_hours > 0),
    -- The host reference must match the host type, in both directions.
    CONSTRAINT ck_deployed_miners_player_host CHECK ((host_type = 'player') = (host_rig_id IS NOT NULL)),
    CONSTRAINT ck_deployed_miners_npc_host    CHECK ((host_type = 'npc') = (host_npc_ref IS NOT NULL)),
    -- Deploying a miner onto your own rig is not a strategy, it is a bookkeeping
    -- accident: self-mining (Invariant I4) is the safe path and it is a different
    -- system entirely.
    CONSTRAINT ck_deployed_miners_not_self   CHECK (deployer_rig_id IS NULL
                                                    OR host_rig_id IS NULL
                                                    OR deployer_rig_id <> host_rig_id),
    CONSTRAINT ck_deployed_miners_row_version CHECK (row_version >= 0)
);

COMMENT ON TABLE deployed_miners IS
    'Parasitic miners (docs/design/04-mining.md §2). Consume the HOST''s compute (Invariant I6); the '
    'only offline income source, buffer-capped (Invariant I5).';
COMMENT ON COLUMN deployed_miners.buffer_wei IS
    'Accrued on-host yield awaiting collection. The prize in a crack (docs/design/04 §5.1) — a transfer, never a faucet.';

-- "Show me my network" and the sweep roll, which is one roll against the whole
-- NPC-hosted network per hour (docs/design/04 §4).
CREATE INDEX ix_deployed_miners_deployer ON deployed_miners (deployer_did, state);
-- "What is running on my machine", the query behind every scan and audit.
-- ⚠ Redundant on H2, and kept anyway. H2 builds its own index for the foreign key on this column,
-- so after the V3–V6 squash the table carries two indexes over `host_rig_id` where the old migration
-- chain carried one — V6's `ALTER COLUMN ... SET DATA TYPE` rebuilt the table and consolidated them.
-- That is the ONLY difference the squash produced (columns, constraints, check clauses, FK rules,
-- triggers, routines and seed data all diffed identical), and the named index stays because it says
-- what the access path is FOR: attributing a deployed miner to the rig whose compute it spends,
-- which is Invariant I6's read. An engine-generated name documents nothing.
CREATE INDEX ix_deployed_miners_host ON deployed_miners (host_rig_id);


-- ---------------------------------------------------------------------------
-- breach_resolutions — what a breach attempt leaves for the economy to read.
--
-- Exactly the four fields docs/design/05-hacking-minigame.md §2 specifies, plus
-- the player and a timestamp. §2 is written to be the part that lasts even
-- though the minigame doc as a whole is [PROPOSAL]: whatever the puzzle turns
-- out to BE, this is the vocabulary the economy consumes.
--
-- ⚠ TIER-GATED, NEVER COUNT-GATED (Invariants I7 and I13). ⚠
--
-- Both readers of this table — proof-of-skill unlocks (docs/design/02 §2.4) and
-- the bot-salvage guard (docs/design/10) — ask "has this player solved class X
-- at tier >= T against a LIVE target". Never "how many times". Count-gating
-- rewards farming the weakest target available. If any query over this table
-- ever reaches for count(*), that is the exploit arriving; the index below is
-- shaped for MAX(difficulty_tier), not for counting.
--
-- [PROPOSAL] vocabularies: `puzzle_class` values are docs/design/05 §3.1 and
-- the 1..5 tier range is §3.3 (open question P-10, expected to change).
-- ⚠ The five classes written here were cut to two by V4 — open question P-1,
-- resolved. This file keeps the original spellings because a migration that has
-- been applied anywhere may not be rewritten; V4 is where the vocabulary is.
-- ---------------------------------------------------------------------------
CREATE TABLE breach_resolutions (
    resolution_id   uuid        PRIMARY KEY,
    player_did      text        NOT NULL,
    puzzle_class    text        NOT NULL,
    difficulty_tier integer     NOT NULL,
    -- Proof-of-skill requires 'live'. A dormant target is still worth loot and
    -- never worth an unlock (docs/design/02 §2.4) — modelled as a named value
    -- rather than a boolean so an inverted flag cannot silently hand out
    -- automation unlocks.
    live_or_dormant text        NOT NULL,
    outcome         text        NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    CONSTRAINT ck_breach_resolutions_player  CHECK (is_did(player_did)),
    CONSTRAINT ck_breach_resolutions_class   CHECK (puzzle_class IN
        ('breach_protocol', 'offset_cipher')),
    CONSTRAINT ck_breach_resolutions_tier    CHECK (difficulty_tier BETWEEN 1 AND 5),
    CONSTRAINT ck_breach_resolutions_target  CHECK (live_or_dormant IN ('live', 'dormant')),
    CONSTRAINT ck_breach_resolutions_outcome CHECK (outcome IN ('breached', 'failed', 'aborted'))
    -- No cross-field validation, deliberately. A failed attempt against a dormant
    -- target is a valid record: this is a log of what happened, not a certificate
    -- of achievement. Rejecting the boring rows would leave an investigator or an
    -- anti-cheat review missing exactly the ones they want.
);

COMMENT ON TABLE breach_resolutions IS
    'resolutionRecord rows (docs/design/05-hacking-minigame.md §2). Read by tier, never by count '
    '(Invariants I7, I13).';

-- Shaped for the only correct question: the highest tier this player has cleared
-- in this class against a live target.
CREATE INDEX ix_breach_resolutions_proof_of_skill
    ON breach_resolutions (player_did, puzzle_class, difficulty_tier DESC);


-- ---------------------------------------------------------------------------
-- Append-only enforcement.
--
-- The ledger is an evidence surface and a provenance chain is a signature over
-- history. Both are things an attacker — or a well-meaning "data fix" — would
-- want to edit in place, and both lose their entire meaning if that succeeds.
-- The service layer intends never to issue such a statement; this makes the
-- intention enforceable by the database, which is the last line of defence on an
-- authoritative server.
--
-- Deliberately a ROW trigger on UPDATE/DELETE only. TRUNCATE is unaffected, so
-- the integration-test harness can still reset between tests without needing a
-- privileged escape hatch that would then exist in production too.
-- ---------------------------------------------------------------------------




CREATE TRIGGER ledger_transactions_append_only BEFORE UPDATE, DELETE ON ledger_transactions FOR EACH ROW CALL "io.github.stoicswe.eyeandsickle.server.persistence.AppendOnlyTrigger";

CREATE TRIGGER provenance_records_append_only BEFORE UPDATE, DELETE ON provenance_records FOR EACH ROW CALL "io.github.stoicswe.eyeandsickle.server.persistence.AppendOnlyTrigger";
